In [2]:
import torch
import numpy as np

In [4]:
# 1. torch 이용 만든 텐서
data = [[1,2], [3,4]]
print(type(data))
x_data = torch.tensor(data)

print(x_data)

# 2. numpy - > torch tensor
np_array = np.array(data)
x_np = torch.from_numpy(np_array)
print(x_np)

<class 'list'>
tensor([[1, 2],
        [3, 4]])
tensor([[1, 2],
        [3, 4]], dtype=torch.int32)


In [5]:
#다른 텐서로부터 생성하기
#명시적으로 재정의(override)하지 않으면, 인자로 주어진 텐서
x_ones = torch.ones_like(x_data) #x_data 속성 유지
print(f'ones tensor:\n{x_ones}')
x_rand = torch.rand_like(x_data, dtype=torch.float) #x_data의 속성을 덮어씀
print(f'random tensor: \n {x_rand}')

ones tensor:
tensor([[1, 1],
        [1, 1]])
random tensor: 
 tensor([[0.3587, 0.5539],
        [0.5109, 0.2222]])


In [6]:
#무작위 또는 상수 값을 나타내기 (randon & constant)
#shape은 텐서의 dimension 을 나타내는 튜플로, 아래 함수들에서는 출력 텐서의 차원을 결정함
shape = (2,3,)
rand_tensor =  torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f'random tensor: {rand_tensor}\n')
print(f'ones tensor: {ones_tensor}\n')
print(f'zeros tensor: {zeros_tensor}\n')

random tensor: tensor([[0.9664, 0.7736, 0.7654],
        [0.4671, 0.1694, 0.0869]])

ones tensor: tensor([[1., 1., 1.],
        [1., 1., 1.]])

zeros tensor: tensor([[0., 0., 0.],
        [0., 0., 0.]])



In [19]:
#텐서의 속성(attribute)
#텐서의 속성은 텐서의 모양(shape), 자료형(datatype) 및 어느 장치에 저장되는지를 나타냄
tensor = torch.rand(3,4)
print(tensor)

device = 'cuda' if torch.cuda.is_available() else 'cpu'
print(device)
tensor.to(device)

print(f'shape of tensor: {tensor.shape}')
print(f'datatype of tensor: {tensor.dtype}')
print(f'device tensor is stored on: {tensor.device}')

tensor([[0.1665, 0.7635, 0.1578, 0.3028],
        [0.6854, 0.9071, 0.8438, 0.1183],
        [0.3146, 0.7622, 0.2320, 0.0063]])
cpu
shape of tensor: torch.Size([3, 4])
datatype of tensor: torch.float32
device tensor is stored on: cpu


In [11]:
#텐서 연산
'''
전치(transposing), 인덱싱(indexing), 슬라이싱(slicing), 수학 계산, 선형 대수, 임의 샘플링(random sampling) 등
 100가지 이상의 텐서 연산들을 여기에서 확인할 수 있음
 각 연산들은 (일반적으로 cpu보다 빠른) gpu에서 실행 할 수 있음
 colab을 사용한다면, edit -> notebook settings 에서 gpu 할당이 가능
 '''

if torch.cuda.is_available():
    tensor = tensor.io('cuda')
print(f'device tensor is sotred on: {tensor.device}')

device tensor is sotred on: cpu


In [22]:
# 표준 인덱싱과 슬라이싱
tensor_1 = torch.ones(4,4)
tensor_1[:,3] = 0

tensor_2 = torch.ones(4,4)
tensor_2[:,1] = 2
print(tensor_1)
print(tensor_2)

tensor([[1., 1., 1., 0.],
        [1., 1., 1., 0.],
        [1., 1., 1., 0.],
        [1., 1., 1., 0.]])
tensor([[1., 2., 1., 1.],
        [1., 2., 1., 1.],
        [1., 2., 1., 1.],
        [1., 2., 1., 1.]])


In [13]:
#텐서 합치기
#torch.cat 을 사용해 주어진 차원에 따라 일련의 텐서를 연결 가능
t1 = torch.cat([tensor, tensor, tensor], dim=1)
print(t1)

tensor([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])


In [23]:
#곱하기
t_mult = tensor_1.mul(tensor_2)
print(t_mult)

print(tensor_1*tensor_2)

tensor([[1., 2., 1., 0.],
        [1., 2., 1., 0.],
        [1., 2., 1., 0.],
        [1., 2., 1., 0.]])
tensor([[1., 2., 1., 0.],
        [1., 2., 1., 0.],
        [1., 2., 1., 0.],
        [1., 2., 1., 0.]])


In [24]:
#행렬 곱
print(tensor_2.matmul(tensor_2.T))
print(tensor_2@tensor_2.T)

tensor([[7., 7., 7., 7.],
        [7., 7., 7., 7.],
        [7., 7., 7., 7.],
        [7., 7., 7., 7.]])
tensor([[7., 7., 7., 7.],
        [7., 7., 7., 7.],
        [7., 7., 7., 7.],
        [7., 7., 7., 7.]])


In [15]:
#텐서 곱하기
#요소별 곱(element-wise product)을 계산함
print(f'tensor.mul(tensor) \n{tensor.mul(tensor)}\n')

#다른 문법
print(f'tensor * tensor \n{tensor * tensor}\n')

tensor.mul(tensor) 
tensor([[0., 0., 0., 0.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

tensor * tensor 
tensor([[0., 0., 0., 0.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])



In [16]:
#두 텐서 간의 행렬 곱(matrix multiplication)을 계산
print(f'tensor.matmul(tensor.T) \n{tensor.matmul(tensor.T)}\n')
# 다른 문법:
print(f'tensor @ tensor.T \n{tensor @ tensor.T}')

tensor.matmul(tensor.T) 
tensor([[0., 0., 0., 0.],
        [0., 4., 4., 4.],
        [0., 4., 4., 4.],
        [0., 4., 4., 4.]])

tensor @ tensor.T 
tensor([[0., 0., 0., 0.],
        [0., 4., 4., 4.],
        [0., 4., 4., 4.],
        [0., 4., 4., 4.]])


In [26]:
t = torch.ones(5)
print(t)
n = t.numpy()
print(n)

t.add(1)
print(t)
print(n)

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]


## 뷰(view) - 원소의 수를 유지하며 텐서의 크기 변경

In [27]:
'''
파이토치 텐서의 뷰는 넘파이의 reshape와 같은 역할
reshape ->텐서의 크기를 변경해주는 역할
'''

t_temp = np.array([[[0,1,2],[3,4,5],[6,7,8], [9,10,11]]])
ft = torch.FloatTensor(t_temp)
print(ft)
print(ft.shape)

#이제 ft view -> 2차원 텐서로 변경
# -1 : 나는 그 값을 모르겠음. 파이토치 니가 알아서 해
#(두번째 차원은 길이는 3 가지도록 하라는 의미임.)
#결론 : 현재 3차원 텐서를 2차원 텐서로 변경하되 (?, 3)의 크기로 변경하라는 의미임.
# 결과적으로 (4,3)의 크기를 가지는 텐서를 얻었음.
# 내부적으로 크기 변환은 다음과 같이 이루어짐. (2, 2, 3) -> (2x 2, 3) -> (4,3)
print(ft.view([-1, 3])) # (?,3)
print(ft.view([-1, 3]).shape)

tensor([[[ 0.,  1.,  2.],
         [ 3.,  4.,  5.],
         [ 6.,  7.,  8.],
         [ 9., 10., 11.]]])
torch.Size([1, 4, 3])
tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]])
torch.Size([4, 3])


In [28]:
'''
스퀴즈 -> 1차원을 제거
스퀴즈는 차원이 1인 경우에는 해당 차원을 제거함.
실습 3x1 크기를 가지는 2차원 텐서 생성
'''

ft = torch.FloatTensor(([0], [1], [2]))
print(ft)
print(ft.shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


In [30]:
'''
해당 텐서는 (3x1)의 크기를 가짐
두번째 차원이 1이므로 squeeze를 사용하면 (3, )의 크기를 가지는 텐서로 변경됨.
'''
print(ft.squeeze())
print(ft.squeeze().shape)

#위의 결과는 1이었는 두번째 차원이 제거되며, 
#(3, )의 크기를 가지는 텐서로 변경되어 1차원 벡터가 된 것을 보여줌.

tensor([0., 1., 2.])
torch.Size([3])


In [31]:
#언스퀴즈 - 특정 위치에 1인 차원을 추가함
# ppt 285 설명 참조

ft=torch.tensor([0,1,2])
print(ft.shape)

print(ft.unsqueeze(0))
print(ft.unsqueeze(0).shape)

print(ft.view(1, -1))
print(ft.view(1, -1).shape)

torch.Size([3])
tensor([[0, 1, 2]])
torch.Size([1, 3])
tensor([[0, 1, 2]])
torch.Size([1, 3])


In [32]:
print(ft.unsqueeze(1))
print(ft.unsqueeze(1).shape)

print(ft.unsqueeze(-1))
print(ft.unsqueeze(-1).shape)

tensor([[0],
        [1],
        [2]])
torch.Size([3, 1])
tensor([[0],
        [1],
        [2]])
torch.Size([3, 1])


In [ ]:
print(ft_temp.view(1,-1))
print(ft_temp.view(-1,1)).shape

tensor([[0.,1.,2.]])
